# Shoreline NARX Model Training Example
Joshua Simmons and Kristen Splinter 

In this notebook, an example is given of how to train a model on the available shoreline data using the NARX model. Results for the publication are generated by running the script 02a_CV_Run_Script.py which saves the fitted models for analysis and plotting.

In [1]:
# magic
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import sys, os, re
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from shoreNARX import TrainingClass
from shoreNARX.plotting import plot_CV_ensemble

## Specify the model configuration
Load the model configuration from a config (json) file. Use the TrainingClass methods to load the correct data in the correct format.

In [3]:
baseLoc = '.'
# First train Narra
narraConfigFile = os.path.join(baseLoc,'config','narra_base_config.json')
# init object
trainObj_narra = TrainingClass(**{'baseDir':baseLoc,'config':narraConfigFile})
# train as per config
trainObj_narra.load_cv_test()
# Load Tairua
tairuaConfigFile = os.path.join(baseLoc,'config','tairua_base_config.json')
# init object
trainObj_tairua = TrainingClass(**{'baseDir':baseLoc,'config':tairuaConfigFile})
# train as per config
trainObj_tairua.load_cv_test()

## Train models
This is just for demonstration and testing. Due to computational demands, the model training is done using the `02a_CV_Run_Script.py` file.

In [25]:
baseLoc = '.'

def train_run(configFile,return_class=False,saveBool=False):
    # init object
    trainObj = TrainingClass(**{'baseDir':baseLoc,'config':configFile})
    if return_class:
        return trainObj
    # train as per config
    res = trainObj.training_wrapper(saveBool=saveBool)
    print(res)
    return trainObj

In [ ]:
# First train Narra
narraConfigFile = os.path.join(baseLoc,'config','narra_base_config.json')
narra_trained = train_run(narraConfigFile)

In [21]:
pd.DataFrame(narra_trained.trainCombsGenerate(10,2,rs=1))

    0  1  2  3  4  5  6  7  8  9
0   1  1  0  0  0  0  0  2  0  0
1   1  1  0  2  0  0  0  0  2  0
2   1  1  0  2  0  2  0  0  0  2
3   1  1  2  0  2  0  2  2  0  0
4   1  1  2  2  0  0  0  2  2  2
5   1  1  0  2  0  2  2  2  2  2
6   1  1  2  2  2  2  2  2  0  2
7   1  1  2  2  2  2  2  2  2  2
8   0  0  1  1  0  0  2  0  0  0
9   0  0  1  1  0  0  0  2  0  2
10  2  0  1  1  0  0  0  2  0  2
11  2  0  1  1  2  0  0  2  0  2
12  2  2  1  1  0  0  2  2  2  0
13  2  2  1  1  2  2  2  0  0  2
14  2  2  1  1  2  0  2  2  2  2
15  2  2  1  1  2  2  2  2  2  2
16  0  0  2  0  1  1  0  0  0  0
17  0  0  0  2  1  1  2  0  0  0
18  0  2  2  0  1  1  0  2  0  0
19  0  0  2  0  1  1  2  2  2  0
20  2  2  0  2  1  1  0  2  0  2
21  0  0  2  2  1  1  2  2  2  2
22  2  0  2  2  1  1  2  2  2  2
23  2  2  2  2  1  1  2  2  2  2
24  0  0  0  0  0  2  1  1  0  0
25  2  0  0  0  2  0  1  1  0  0
26  0  0  0  2  2  0  1  1  2  0
27  2  0  0  2  2  0  1  1  2  0
28  2  2  2  0  0  2  1  1  2  0
29  2  2  0  0  2  2  1  1  2  2
30  0  2  2  2  2  2  1  1  2  2
31  2  2  2  2  2  2  1  1  2  2
32  0  0  0  0  2  0  0  0  1  1
33  0  0  2  2  0  0  0  0  1  1
34  0  0  2  0  2  0  2  0  1  1
35  2  2  2  0  0  0  0  2  1  1
36  0  0  2  2  2  0  2  2  1  1
37  2  2  2  2  2  2  0  0  1  1
38  2  2  2  2  0  2  2  2  1  1
39  2  2  2  2  2  2  2  2  1  1

In [ ]:
# Then Tiarua
tairuaConfigFile = os.path.join(baseLoc,'config','tairua_base_config.json')
tairua_trained = train_run(tairuaConfigFile)

# Show model performance

In [8]:
for thisFold in np.arange(narra_trained.statsOut[0].__len__()):
    plot_CV_ensemble(
        narra_trained.statsOut,
        thisFold
    )

AttributeError: 'TrainingClass' object has no attribute 'statsOut'

In [ ]:
for thisFold in np.arange(narra_trained.statsOut[0].__len__()):
    plot_CV_ensemble(
        tairua_trained.statsOut,
        thisFold
    )